server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    session:
      cookie:
        http-only: true
    register-default-servlet: true

spring:
  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/sns
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 40
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true

logging:
  level:
    org.hibernate.SQL: debug